### ISSUE TITLE
Logging Frequency

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/trixi#11]
Hi, 
Is there a possibility to introduce a logging frequency to trixi's logging?

The problem is: Visdom caches everything that has been logged into the RAM which causes a memory overflow if training several networks on the same machine.

A logging frequency in combination with a logging_behavior mith be a good solution to this:
the logging frequency would define, how often values will be logged and the logging behavior would define, what kind of values would be logged (e.g. all values between the logged ones will be skipped, or the mean of all values since the last logged value will be logged).

This could also improve another problem: If logging many values, the background processes used for logging are really slow, causing the logging to be far behind the actual training state.

Do you plan to integrate such a feature or would you be open for a PR adressing this?

Best,
Justus

**Comment by jenspetersen** [comment]
The PytorchExperiment already has this feature, but if you're using only the plain loggers, I don't think that's something we will integrate. I like to think of the loggers as a separate API that I can call, and what you describe would require an internal state that reflects the status of a given experiment (granted, VisdomLogger instances are usually tied to a single experiment instance, but that's not necessarily the case for other loggers). Unless I misunderstood what you meant, I think you'll have to build that on your end...

@dzimmerer any thoughts?

**Comment by dzimmerer** [comment]
As Jens said, the combined logger already offers a logging frequency ( and some not very fancy hard coded behavior), and I don't think it would make sense to integrate it into the loggers directly. 
However feel free to completely overhaul, extend,... the combined logger or propose another wrapper for the loggers =) .

**Comment by justusschock** [comment]
In my opinion this feature would belong into the logger (not the experiment) and might be helpfull for every logger (e.g. if using a file logger or plot logger, you would have lots of image files); 
It should be possible to integrate this to all loggers and set a default value, which would keep the current behavior unchanged.

I'll have a look how to integrate that at my end.

Thank you very much!

**Comment by dzimmerer** [comment]
@justusschock , perhaps my response was not very clear and a little misleading, I was not proposing to integrate it into the experiment, but rather to write a common wrapper, which can wrap all loggers. 
In my opinion, a logger on its own should keep as little state as possible (and they already have too much internal "states" for my taste). 
And since the behavior and the frequency would be common for all loggers, I think it would make sense to outsource the logic to a sperate wrapper (or sth similar).

If you find an elegant solution we would be very happy to integrate it =) .

Cheers
