### ISSUE TITLE
Move tensorboardX from trixi to trixi-slim

### ISSUE THREAD

**Issue by ORippler** [MIC-DKFZ/trixi#12]
Imo, tensorboardX should be moved from trixi to trixi-slim. It provides core logging functionality similar to visdom, which is included in trixi-slim and [itself only depends on numpy, six and protobuf](https://github.com/lanpa/tensorboardX/blob/master/setup.py#L33).

**Comment by ORippler** [comment]
Also, tensorboard logging seems to be missing from both trixi and trixi-slim on pypi. Any ETA on when they will be officially released?

**Comment by jenspetersen** [comment]
We're deploying from master, but the default branch you see on Github is develop, so not everything you see there is supposed to be on PyPI. We're doing the bulk of the work on Fridays every two weeks, the next session is in 4 days, maybe then, but I wouldn't bet on it. @dzimmerer can you comment on the progress? With respect to integrating it into trixi-slim, I guess that's something we can do.

**Comment by jenspetersen** [comment]
Is now on master and PyPI. Starting from v0.1.2.1 tensorboardX is in trixi-slim.
