### ISSUE TITLE
Dependencies breaking

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/trixi#15]
Hi,

I just noticed, that in your [utils](https://github.com/MIC-DKFZ/trixi/blob/develop/trixi/util/util.py#L23), you are using `scipy.misc.imsave`. This function was deprecated in scipy 1.0 and removed in newer releases, which causes imports to break with your requirement scipy>=0.19.1.

You'd have to adapt either your requirement or the import (the function was moved to imageio).

Best,
Justus

**Comment by jenspetersen** [comment]
Hi Justus, thanks for pointing that out! We will shortly release an update to fix this and some other stuff :)

**Comment by dzimmerer** [comment]
Should be fixed now.

**Comment by justusschock** [comment]
Did you release the new packages on PyPi? My CI/CD usually installs the latest PyPi packages and they are still breaking

**Comment by jenspetersen** [comment]
No, it's only on develop atm

**Comment by justusschock** [comment]
Do you have an ETA for the next release?

**Comment by jenspetersen** [comment]
Hopefully Friday :)

**Comment by jenspetersen** [comment]
Had to do MICCAI rebuttals -.-

**Comment by justusschock** [comment]
No worries. Is there anything left to do for a new release (something I may be able to help with)?

**Comment by jenspetersen** [comment]
New release is on PyPI, feel free to reopen if anything's not working.
