### ISSUE TITLE
slackclient 2.X breaks trixi

### ISSUE THREAD

**Issue by giladfr-rnd** [MIC-DKFZ/trixi#16]
slackclient released version 2.0.1 with a new  package structure, and it breaks any new install of trixi:
running
```
pip install -e .
```

To work around #15:

```
pip install scipy==1.1.*
```

And then:

```
pytest
```

everything fails since `pytorchexperiment` can't be imported.

To fix this you need to:
```
pip install slackclient==1.*
```

**Comment by jenspetersen** [comment]
Thanks for pointing this out! As you mention, slackclient changed their API between versions 1 and 2, and we will probably move to v2 with the next update.

**Comment by dzimmerer** [comment]
Should be fixed now.
