### ISSUE TITLE
Error of get_vars_from_sys_argv() in pytorchexperiment.py

### ISSUE THREAD

**Issue by BostonLobster** [MIC-DKFZ/trixi#21]
In the `get_vars_from_sys_argv()` function within `pytorchexperiment.py`, you use 

>return param.get("config_path"), param.get("resume_path")

to get the config/resume path.

However, `param` here is an argparse.Namespace object, which does not have a `get` method. And if one specify `parse_sys_argv=True` during the initialization of a PytorchExperiment, he will get 

> AttributeError: 'Namespace' object has no attribute 'get'

**Comment by jenspetersen** [comment]
Good call, thanks for pointing that out. I fixed it on develop. You'll have to wait for the next release for the fix to make it to master/PyPI though :/
