### ISSUE TITLE
setting port 

### ISSUE THREAD

**Issue by ECarboni** [MIC-DKFZ/trixi#23]
Is it possible to set the port for visdom in trixi? if so how? I can manually do "python -m visdom.server -port=8890" but if I use the "PytorchExperiment" class to automatically start visdom (like in your UNet Example) I do not know where to specify the port....

**Comment by dzimmerer** [comment]
For the loggers in the PytorchExperiment you can give the logger specific parameters as kwargs as a dict : PytorchExperiment(loggers = {"visdom": ("visdom", {"port": 8890, "auto_start_ports":8890 }))

Hope that helps.
