### ISSUE TITLE
Regarding the Model Structure plot

### ISSUE THREAD

**Issue by CBD88** [MIC-DKFZ/trixi#24]
Hi, How can i see the output created by this code: "self.vlog.plot_model_structure(self.model,                                   [self.config.batch_size, 1, 28, 28], name='Model Structure')"

**Comment by jenspetersen** [comment]
Is your Visdom server active?

**Comment by CBD88** [comment]
No

Sent from Yahoo Mail on Android 
 
  On Fri, 3 Jul 2020 at 4:56 pm, Jens Petersen<notifications@github.com> wrote:   


Is your Visdom server active?

**Comment by jenspetersen** [comment]
`python -m visdom.server --port 8080` will set up a Visdom server with our default port. self.vlog is a VisdomLogger instance that will log to the server. You can see the output in your browser at localhost:8080.
