### ISSUE TITLE
You could include an easy citation for yourselves in the readme?

### ISSUE THREAD

**Issue by EmmaRocheteau** [MIC-DKFZ/trixi#27]

**Comment by jenspetersen** [comment]
Good point. I just added one (could be a few minutes until it's synched to Github). Reminds me that we should update our CI to automatically publish to Zenodo at one point...

**Comment by EmmaRocheteau** [comment]
Great! I've cited you in the paper that I'm just about submit!

**Comment by jenspetersen** [comment]
That's awesome, thank you. Good luck with the submission!
