### ISSUE TITLE
support for tensorflow

### ISSUE THREAD

**Issue by MaxBenChrist** [MIC-DKFZ/trixi#3]
hey guys, 

interesting project! I was wondering if you are considering to add tensorflow support at some point in the future? 

cheers 

Max

**Comment by GregorKoehler** [comment]
Hi Max,

correct me if I'm wrong there @dzimmerer, but I think it's on the list!

Cheers
Gregor

**Comment by dzimmerer** [comment]
Hi,

Thanks =).
I think its somewhere on the list (along with a better tensorboard support) but does not have a high priority since tensorboard (and many other frameworks for tf) are already quite good and we focus more on PyTorch. Perhaps with TF 2.0 and a more eager mode oriented execution, it will get a higher priority. 

Cheers,
David

**Comment by MaxBenChrist** [comment]
I have not tried trixi yet. Have to spin it up sometime next week ;).

My Background: We at othoz use ml/deep learning to develop trading strategies. Hence, we constantly have to evaluate new strategies, models etc. We are looking to develop a research platform that allows us to plan, organise, archive and orchestrate ml experiments like grid searches, backtests etc.

We also wrote a master thesis proposal to look for a good student that helps us to develop that platform
https://www.dropbox.com/s/tojebbzozacbn0n/20181122_othoz_master_thesis_proposal_research_platform_02.pdf?dl=0&fbclid=IwAR1uc0hWjn0yNyAC-X7VSwlc8ix0ak7qC5oN3J-zxl-czpKEQFpTOB4lKX0

If you know an student with python programming experience that wants to dip into ml in finance and collect experience bringing ml into production, feel free to share the proposal :)

In contrast to the finance world in general, we are pretty open to open source contributions. We are already planning to open source major parts of our stack, see https://github.com/Othoz

So, maybe a tool like trixi could be part of our research platform, I am not sure yet. We still haven't decided on the tools/technologies that we want to deploy. Anyway our models are mostly implemented in tensorflow, so that is a hard constraint. We need tensorflow support. But, maybe we can collaborate over that master thesis and extend the trixi tensorflow support? the student could extend the trixi tensorflow support and adapt it our needs.

**Comment by jenspetersen** [comment]
Orchestration and proper grid search is something we haven't really tackled yet. There is a rudimentary grid search iterator I built for myself in the utils, but it sounds like you would like something that would automatically deploy jobs to the cloud. We certainly thought about that but realistically that won't happen in the near future... I guess you could look into our abstract Experiment class and also the ExperimentLogger. Those are framework agnostic (using numpy) and would allow you to have a consistent output structure, which is what you will need in any case :) I only know the students from our group who of course already have projects, so we can't help you there...
