### ISSUE TITLE
No module named 'trixi.logger'

### ISSUE THREAD

**Issue by qiang92** [MIC-DKFZ/trixi#6]
ubuntu 16.04 python 3.6 
I succeeded to install trixi. And I want to try your "pytorch_example.ipynb", it shows No module named 'trixi.logger'? I don't know why?

**Comment by jenspetersen** [comment]
This was because of an issue in our setup.py, but should be solved now, both for pypi and github install. If you have version 0.1.1.1 and still encounter problems of this kind, please let us know! Also, thanks for trying trixi 😊
