### ISSUE TITLE
Improve consistency of `counter` use for tensorboard logging

### ISSUE THREAD

**Issue by ORippler** [MIC-DKFZ/trixi#8]
Hi all,

I think the consistency of tensorboard logging with regards to the `counter` argument could be improved. I would suggest using `self.val_dict` for all logging operations and using `counter` only to override the internal state of `self.val_dict[key]`, similar as is used in [`show_value`](https://github.com/MIC-DKFZ/trixi/blob/develop/trixi/logger/tensorboard/tensorboardxlogger.py#L47).

In [`show_image_grid`](https://github.com/MIC-DKFZ/trixi/blob/develop/trixi/logger/tensorboard/tensorboardxlogger.py#L56), `counter` is directly used as the global_step, forcing the user to keep an external counter for every image_grid that is provided at every logging call.

**Comment by dzimmerer** [comment]
Thanks for the feedback =) , we'll look into that. 

The tensorboard logger is currently in development/ testing so there might take some time and be a few changes.

**Comment by dzimmerer** [comment]
@ORippler correct me if I'm wrong, but I think tensorboard automatically increases an internal counter for data with the same name if no counter is given ( I think it displays a slider, with which you can see all images at consecutively).

**Comment by ORippler** [comment]
So tensorboard itself just parses the summary files generated by the `FileWriter`, and the slider/visualization is constructed by tensorboard based on the time_stamp-ordered list of all `counters` for all named Summaries. For each named Summary, it checks whether all `counters` (mapped to event.step) in this list are ascending, and in case of mismatch throws an `out of order event` and discards all data until `counters` are again ascending (see [here](https://github.com/lanpa/tensorboardX/issues/6)).

[Tensorboard](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/summary/writer/writer.py#L274) and [TensorboardX](https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py#L137) `FileWriter` themself do not keep an internal counter, which is why i get out_of_order events for images logged by `show_image_grid`, but not for scalars logged by `show_value`. In terms of consistency, I suggest tensorboard logging to behave identical to Visdomlogging in trixi, where [a counter is used](https://github.com/MIC-DKFZ/trixi/blob/develop/trixi/logger/visdom/numpyvisdomlogger.py#L62). Your [TensorboardXLogger](https://github.com/MIC-DKFZ/trixi/blob/develop/trixi/logger/tensorboard/tensorboardxlogger.py#L19) already possesses the same `structured_dict` stored in `self.val_dict`, but is currently only used for `self.show_value` but not `self.show_image_grid`

While tensorflow does have the `tf.train.global_counter()` (a tensor that is automatically incremented by 1 every time it is evaluated inside a `tf.Session()` object), this would then have to be explicitly passed by the user as the `counter` argument to your `TensorboardXLogger`, which is then an external counter variable that introduces inconsistent behaviour across trixi-loggers imo.

Best,
ORippler

**Comment by ORippler** [comment]
Here is where I quickly hacked the same usage of `self.val_dict` for `show_image_grid` as for `show_value`. Cleanest solution would be to just setup a decorator functrion imo

[tensorboardxlogger.txt](https://github.com/MIC-DKFZ/trixi/files/2792150/tensorboardxlogger.txt)

**Comment by ORippler** [comment]
Sure can do. Is there like a milestone or something I can assign this PR to?

This needs to be additionally performed for all other member functions of `TensorboardXLogger`, such as `show_barplot` etc...

Also, it would be nice to make the logging operations multi-threaded as with the visdomlogger, they can otherwise be quite the bottleneck. I will gladly contribute if you point me to the corresponding design you would like to follow.

**Comment by jenspetersen** [comment]
Integrated this on develop, will be part of next release. Multithreading needs some more work though.
