### ISSUE TITLE
Missing Dependency warnings

### ISSUE THREAD

**Issue by justusschock** [MIC-DKFZ/trixi#9]
If dependency modules are not installed, a warning is raised.

E.g. if  `torch` is missing, the raised Warning is:
```
Could not import Pytorch related modules.
No module named 'torch'
```
I would like to make this a `ImportWarning` to make this filterable (e.g. the same warning is only shown once or completely ignored).

Is it okay, if I open a PR on this? On which branch should I start working?

**Comment by jenspetersen** [comment]
We only mirror our working repo to Github, so I'm not sure how easy it'll be to export the pull request and apply to ours, but it should be possible. Seeing that the the changes you describe are minor, maybe we could just try?

**Comment by jenspetersen** [comment]
Integrated into develop branch.
